package: speed_up
version: '1.3.0'
author: 'Alexander Walther'
supportpage: https://www.alexplus.de

requires:
    redaxo: ^5.10
    yrewrite: ^2.7
    metainfo: ^2

page:
    hidden: true

pages: 
    system/speed_up:
        title: Speed Up
        perm: admin
        icon:  rex-icon fa-rocket
        pjax: true

default_config:
    profile: 'auto'
    prefetch: '<!--<link rel="prefetch" href="/pfad/zu/meiner/datei.ext">-->'
    preload: '<!--<link rel="preload" href="/pfad/zu/meiner/datei.ext">-->'
    cache_warmup: 'auto'
