package: speed_up
version: '1.0.1'
author: 'Alexander Walther'
supportpage: https://www.alexplus.de

requires:
    redaxo: ^5.6
    yrewrite: ^2

page:
    hidden: true

pages: 
    system/speed_up:
        title: Speed Up
        perm: admin
        pjax: true

default_config:
    profile: 'auto'
    prefetch: '<!--<link rel="prefetch" href="/pfad/zu/meiner/datei.ext">-->'
    preload: '<!--<link rel="preload" href="/pfad/zu/meiner/datei.ext">-->'
